coverage:
  status:
    patch: false
    project:
      default:
        target: auto
        threshold: 1%
comment:
  layout: "header"
  behavior: default
  require_changes: false
ignore:
  - "kim_property/_version.py"
